user/niri: update to 26.04
Tests no longer fail, 32-bit still oddly broken; using
RUST_LIBC_UNSTABLE_MUSL_V1_2_3 env fixes libc-nix
interaction but pipewire still has issues like

error[E0063]: missing fields `_bitfield_1` and `_bitfield_align_1` in initializer of `libspa_sys::timespec`

Closes https://github.com/chimera-linux/cports/pull/5490
Closes https://github.com/chimera-linux/cports/pull/5494